apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - externalsecret-grafana.yaml
  - configmap-datasources.yaml
  - deployment-grafana.yaml
  - service-grafana.yaml
