apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-app
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: backstage-app
    creationPolicy: Owner
  data:
    - secretKey: app-config.yaml
      remoteRef:
        key: platform/backstage/app-config
        property: config
